micronaut:
  application:
    name: quizdevCore
  data:
    pageable:
      default-page-size: 10
datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:migrations
