datasources:
  default:
    url: ${PROD_MIGRATION_DB_URL}
    username: ${PROD_MIGRATION_DB_USERNAME}
    password: ${PROD_MIGRATION_DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
flyway:
  datasources:
    default:
      default-schema: quizdev_core
      enabled: true
